### ISSUE TITLE
I set the exec path of QtCreator  and setting in the vscode but I still  can't Edit in  QtCreator or Designer

### ISSUE THREAD

**Issue by xuyiqun-learner** [andisfar/LaunchQtCreator#3]
Ubuntu 18.04
QtCreator4.9.2
setting.json : 
    "qttools.creator": "/home/###/QtCreator/latest/bin/qtcreator",
    "qttools.extraSearchDirectories": ["/home/###/QtCreator/latest"]
I thought I got everything right but it doesn't make sense either.

**Comment by andisfar** [comment]
qttools.creator and qttools.extraSearchDirections are not provided nor supported by LaunchQtCreator, must be for a different extension.
The first time you run LaunchQtCreator extension to launch either QtCreator or Designer, a File Dialog will be displayed in order to allow you to point to the executable you want to use, and then that path will be stored in the Extensions settings for future use

**Comment by andisfar** [comment]
Thank your for reaching out to me, your input is appreciated.

If you feel this is still an issue, please let me know.
As I believe that this is not an issue related to the functionality of LanuchQtCreator, I am closing this issue.

V/R,

Oral Shane Curtis

**Comment by andisfar** [comment]
Issue is related to a different extension, not LaunchQtCreator
